version: '3'
services:
    packages:
        container_name: packages
        volumes:
            - ./:/usr/app
        build:
            context: ./
        restart: always
        environment:
            - APP_PORT=8080
            - DB_HOST=postgres
            - REDIS_HOST=redis
        ports:
            - '8080:8080'
        depends_on:
            - redis
            - postgres
        links:
            - postgres
            - redis
    redis:
        image: 'redis:latest'
        container_name: microservice-redis
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'
        labels:
            kompose.service.type: nodeport
        command:
            - redis-server
            - '--bind'
            - redis
            - '--port'
            - '6379'
        volumes:
            - 'redis_data:/usr/local/etc/redis/redis.conf'
        ports:
            - '6379:6379'
    postgres:
        image: postgres:13.0-alpine
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - '5434:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=reaql-dev
        container_name: postgres_dev
volumes:
    redis_data:
        driver: local
