name: Testing

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '15']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install required Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Npm install
        run: npm i

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Node test
        env:
          NODE_ENV: test

        run: npm run test
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '15']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install required Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Npm install
        run: npm i

      - name: Node lint
        run: npm run lint
